"""init

Revision ID: 1ba0a7567b1f
Revises: 
Create Date: 2026-05-20 00:50:57.765046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ba0a7567b1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('score_direction', sa.String(length=4), nullable=False),
    sa.Column('min_score', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("score_direction in ('desc','asc')", name='ck_games_score_direction'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_slug'), ['slug'], unique=True)

    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_actions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_admin_user_id'), ['admin_user_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed', sa.String(length=64), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index('ix_scores_game_deleted', ['game_id', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_game_id'), ['game_id'], unique=False)
        batch_op.create_index('ix_scores_game_score', ['game_id', 'score'], unique=False)
        batch_op.create_index('ix_scores_game_seed_score', ['game_id', 'seed', 'score'], unique=False)
        batch_op.create_index('ix_scores_game_submitted', ['game_id', 'submitted_at'], unique=False)
        batch_op.create_index('ix_scores_player_name', ['player_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index('ix_scores_player_name')
        batch_op.drop_index('ix_scores_game_submitted')
        batch_op.drop_index('ix_scores_game_seed_score')
        batch_op.drop_index('ix_scores_game_score')
        batch_op.drop_index(batch_op.f('ix_scores_game_id'))
        batch_op.drop_index('ix_scores_game_deleted')

    op.drop_table('scores')
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_actions_admin_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_action'))

    op.drop_table('admin_actions')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_slug'))

    op.drop_table('games')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
